# Generated by Django 6.0.2 on 2026-02-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('local_video_path', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp_seconds', models.IntegerField(db_index=True)),
                ('timestamp_formatted', models.CharField(blank=True, default='', max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('subtitle_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='videos.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'timestamp_seconds'], name='videos_extr_video_i_7c8f5b_idx')],
                'unique_together': {('video', 'timestamp_seconds')},
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('kind', models.CharField(choices=[('video', 'video'), ('subtitle', 'subtitle'), ('thumbnail', 'thumbnail'), ('meta', 'meta'), ('other', 'other')], default='other', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videos.video')),
            ],
            options={
                'unique_together': {('video', 'file_path')},
            },
        ),
    ]
