# Generated by Django 6.0.2 on 2026-02-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset_seconds', models.IntegerField(default=0)),
                ('interval_seconds', models.IntegerField(default=60)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('full_duration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='quizgen.generationjob')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('character', 'Character'), ('setting', 'Setting'), ('feeling', 'Feeling'), ('action', 'Action'), ('causal', 'Causal'), ('outcome', 'Outcome'), ('prediction', 'Prediction')], max_length=32)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('llm_rank', models.IntegerField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='quizgen.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentLLMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('best_question', models.TextField(blank=True, default='')),
                ('has_error', models.BooleanField(default=False)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_result', to='quizgen.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='submitted', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_sets', to='videos.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['video', 'start_seconds', 'end_seconds'], name='quizgen_seg_video_i_a01b4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('video', 'start_seconds', 'end_seconds')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedquestion',
            unique_together={('segment', 'qtype')},
        ),
    ]
