//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::frames::Entity as Frames;
pub use super::kid_tags::Entity as KidTags;
pub use super::kids::Entity as Kids;
pub use super::parents::Entity as Parents;
pub use super::questions::Entity as Questions;
pub use super::segments::Entity as Segments;
pub use super::tags::Entity as Tags;
pub use super::video_assignments::Entity as VideoAssignments;
pub use super::video_tags::Entity as VideoTags;
pub use super::videos::Entity as Videos;
