//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "questions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub qtype: String,
    pub question: String,
    pub answer: String,
    pub rank: Option<i32>,
    pub segment_id: i32,
    pub followup_enabled: Option<bool>,
    pub followup_correct_question: Option<String>,
    pub followup_correct_answer: Option<String>,
    pub followup_wrong_question: Option<String>,
    pub followup_wrong_answer: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::segments::Entity",
        from = "Column::SegmentId",
        to = "super::segments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Segments,
}

impl Related<super::segments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Segments.def()
    }
}
