//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[schema(value_type = String, format = "date-time", example = "2026-01-15T10:30:00Z")]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = String, format = "date-time", example = "2026-01-15T10:30:00Z")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::kid_tags::Entity")]
    KidTags,
    #[sea_orm(has_many = "super::video_tags::Entity")]
    VideoTags,
}

impl Related<super::kid_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KidTags.def()
    }
}

impl Related<super::video_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoTags.def()
    }
}
