//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "videos")]
pub struct Model {
    #[schema(value_type = String, format = "date-time", example = "2026-01-15T10:30:00Z")]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = String, format = "date-time", example = "2026-01-15T10:30:00Z")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: String,
    pub title: Option<String>,
    pub thumbnail_url: Option<String>,
    pub duration_seconds: Option<i32>,
    pub local_video_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::segments::Entity")]
    Segments,
    #[sea_orm(has_many = "super::video_assignments::Entity")]
    VideoAssignments,
    #[sea_orm(has_many = "super::video_tags::Entity")]
    VideoTags,
}

impl Related<super::segments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Segments.def()
    }
}

impl Related<super::video_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoAssignments.def()
    }
}

impl Related<super::video_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoTags.def()
    }
}
