//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::controllers::answers::Answer;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "video_assignments")]
pub struct Model {
    #[schema(value_type = String, format = "date-time", example = "2026-01-15T10:30:00Z")]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = String, format = "date-time", example = "2026-01-15T10:30:00Z")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub kid_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub video_id: String,
    #[schema(value_type = Option<[Answer]>)]
    pub answers: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kids::Entity",
        from = "Column::KidId",
        to = "super::kids::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Kids,
    #[sea_orm(
        belongs_to = "super::videos::Entity",
        from = "Column::VideoId",
        to = "super::videos::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Videos,
}

impl Related<super::kids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Kids.def()
    }
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Videos.def()
    }
}
