# Generated by Django 6.0.2 on 2026-02-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizgen', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_sets', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField(blank=True, null=True)),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('final_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='review.finalquestionset')),
            ],
            options={
                'unique_together': {('final_set', 'start_seconds', 'end_seconds')},
            },
        ),
        migrations.CreateModel(
            name='FinalAIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('character', 'Character'), ('setting', 'Setting'), ('feeling', 'Feeling'), ('action', 'Action'), ('causal', 'Causal'), ('outcome', 'Outcome'), ('prediction', 'Prediction')], max_length=32)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('llm_ranking', models.IntegerField(blank=True, null=True)),
                ('expert_ranking', models.IntegerField(blank=True, null=True)),
                ('trashed', models.BooleanField(default=False)),
                ('final_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='review.finalsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('review', 'Review'), ('create', 'Create')], default='review', max_length=16)),
                ('segment_index', models.IntegerField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('skip', 'skip'), ('character', 'Character'), ('setting', 'Setting'), ('feeling', 'Feeling'), ('action', 'Action'), ('causal', 'Causal'), ('outcome', 'Outcome'), ('prediction', 'Prediction')], default='skip', max_length=32)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('best_question', models.JSONField(blank=True, default=dict)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_annotations', to='quizgen.segment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_annotations', to='videos.video')),
            ],
            options={
                'unique_together': {('segment', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='ExpertQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start', models.FloatField()),
                ('segment_end', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('skipped', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True, default='')),
                ('question_type', models.CharField(blank=True, choices=[('character', 'Character'), ('setting', 'Setting'), ('feeling', 'Feeling'), ('action', 'Action'), ('causal', 'Causal'), ('outcome', 'Outcome'), ('prediction', 'Prediction')], default='', max_length=32)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_questions', to='videos.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'segment_start', 'segment_end'], name='review_expe_video_i_443c2b_idx')],
            },
        ),
    ]
