# Generated by Django 6.0.2 on 2026-03-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalaiquestion',
            name='followup_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finalaiquestion',
            name='followup_question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
