# Generated by Django 6.0.2 on 2026-03-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_finalaiquestion_followup_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalaiquestion',
            name='followup_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalaiquestion',
            name='followup_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
