# Generated by Django 6.0.2 on 2026-03-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_finalaiquestion_followup_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalaiquestion',
            old_name='followup_answer',
            new_name='followup_for_correct_a',
        ),
        migrations.RenameField(
            model_name='finalaiquestion',
            old_name='followup_question',
            new_name='followup_for_correct_q',
        ),
        migrations.AddField(
            model_name='finalaiquestion',
            name='followup_for_incorrect_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalaiquestion',
            name='followup_for_incorrect_q',
            field=models.TextField(blank=True, null=True),
        ),
    ]
